// =============================================================================
// CustomFunctionsLibrary -- M.pq
// -----------------------------------------------------------------------------
// This query loads all functions from the PQ Custom Library on GitHub and
// exposes them as a record. Functions are called as:
//
//   M[Category.FunctionName](arg1, arg2, ...)
//
// SETUP:
//   1. Paste this entire file into a blank Power Query Advanced Editor window.
//   2. Rename the query to "M".
//   3. Set the PAT parameter (see below) to a GitHub Personal Access Token with
//      read-only Contents scope for the ciden6481/CustomFunctionsLibrary repo.
//      In Power BI Service, set this as a dataset parameter before publishing.
//
// HOW TO CREATE A PAT:
//   https://docs.github.com/en/authentication/keeping-your-account-and-data-secure/managing-your-personal-access-tokens
//
// NOTE: This file is auto-generated by M_Creator.py. Do not edit the native
//       function environment block manually -- run M_Creator.py instead.
// =============================================================================

let
    // --- Configuration --------------------------------------------------------
    GitHubUser      = "ciden6481",
    GitHubRepo      = "CustomFunctionsLibrary",
    FunctionsPrefix = "PQ Custom Library/Functions/",
    BaseURL         = "https://api.github.com/repos/",
    PAT             = "",  // <-- Paste your GitHub PAT here, or set via dataset parameter

    // --- Auth headers ---------------------------------------------------------
    QueryHeaders = if PAT <> ""
        then [Authorization = "Bearer " & PAT]
        else [],

    // --- Get full recursive tree in one API call ------------------------------
    RawTree = Json.Document(
        Web.Contents(
            BaseURL,
            [
                RelativePath = GitHubUser & "/" & GitHubRepo & "/git/trees/main",
                Query        = [recursive = "1"],
                Headers      = QueryHeaders
            ]
        )
    )[tree],

    // --- Build a table from the tree and filter to function .pq files ---------
    TreeTable     = Table.FromList(RawTree, Splitter.SplitByNothing(), null, null, ExtraValues.Error),
    Expanded      = Table.ExpandRecordColumn(TreeTable, "Column1", {{"path", "sha", "type"}}, {{"Path", "Sha", "Type"}}),
    FunctionFiles = Table.SelectRows(
        Expanded,
        each [Type] = "blob"
            and Text.StartsWith([Path], FunctionsPrefix)
            and Text.EndsWith([Path], ".pq")
    ),

    // --- Derive "Category.FunctionName" keys from file paths ------------------
    // Input:  "PQ Custom Library/Functions/Date/QuarterLabel.pq"
    // Output: "Date.QuarterLabel"
    WithRelPath = Table.AddColumn(
        FunctionFiles,
        "RelPath",
        each Text.Replace(
                Text.Replace([Path], FunctionsPrefix, ""),
                ".pq", ""
             )
    ),
    WithName = Table.AddColumn(
        WithRelPath,
        "Name",
        each Text.Replace([RelPath], "/", ".", Replacer.ReplaceText)
    ),

    // --- Helper: fetch raw base64 blob content from GitHub --------------------
    GetBlob = (sha as text) =>
        Json.Document(
            Web.Contents(
                BaseURL,
                [
                    RelativePath = GitHubUser & "/" & GitHubRepo & "/git/blobs/" & sha,
                    Query        = [],
                    Headers      = QueryHeaders
                ]
            )
        )[content],

    // --- Helper: evaluate blob as an M expression (returns a function) --------
    EvaluateBlob = (sha as text) =>
        let
            raw     = GetBlob(sha),
            decoded = Text.FromBinary(Binary.FromText(raw)),
            result  = Expression.Evaluate(
                decoded,
                [
                    // Native M functions available to evaluated library functions.
                    // This block is auto-generated by M_Creator.py -- do not edit manually.
                    Date.Month = Date.Month,
                    Date.Year = Date.Year,
                    Number.Abs = Number.Abs,
                    Number.IntegerDivide = Number.IntegerDivide,
                    Number.Mod = Number.Mod,
                    Number.ToText = Number.ToText,
                    Value.ReplaceType = Value.ReplaceType
                    // Web.Contents is intentionally excluded -- it causes a dynamic
                    // data source error in Power BI Service when inside Expression.Evaluate.
                    // Library functions must not call Web.Contents directly.
                ]
            )
        in
            result,

    // --- Helper: return raw text for non-evaluatable blobs --------------------
    GetRawText = (sha as text) =>
        Text.FromBinary(Binary.FromText(GetBlob(sha))),

    // --- Fetch + evaluate every function file ---------------------------------
    WithValue = Table.AddColumn(
        WithName,
        "Value",
        each try EvaluateBlob([Sha]) otherwise GetRawText([Sha])
    ),

    // --- Build the output record: {{ "Date.QuarterLabel" = <function>, ... }} --
    FinalTable   = Table.SelectColumns(WithValue, {{"Name", "Value"}}),
    OutputRecord = Record.FromTable(FinalTable)

in
    OutputRecord
